### PR TITLE
Process metadata from Pandoc through Pelican

### PR DESCRIPTION
**Pull request by nandac**
Thanks to the code snippet provided by @ErwinJanssen this commit removes the limitation of having only single-level YAML metadata as document frontmatter.

### CODE REVIEW

**Review by justinmayer — APPROVED** [review]
Looks good to me. What do you think, @ErwinJanssen?

**Comment by nandac** [comment]
@justinmayer Could you please merge this?

I have a number of PRs that I need to make and I am also in the process of making some significant changes to the code to make it faster in my own sandbox.

**Comment by justinmayer** [comment]
Nice work on this, Nanda. 💫

**Comment by ErwinJanssen** [comment]
> Looks good to me. What do you think, @ErwinJanssen?

Looks good overall! I saw some room for improvement in this PR, but for the most part that is already covered by the other PRs that are merged now.

**Pull request merged**
