### PR TITLE
Require Python 3.8+

### PR DESCRIPTION
**Pull request by justinmayer**
- Require Python 3.8+ (Python 3.7 soon goes [end-of-life](https://endoflife.date/python))
- Update linter dependency versions
- Add pyupgrade & unimport hooks to pre-commit config
- Enhance GitHub Actions CI workflow
- Fix build status badge

### CODE REVIEW

**Comment by justinmayer** [comment]
@nandac: The changes in this PR [passed CI without any problems](https://github.com/pelican-plugins/pandoc-reader/actions/runs/4669973237?pr=30) a few months ago, but now the tests are failing even though nothing in this PR has changed. Do you have any idea what needs to be changed in order to fix the failing tests?

**Comment by justinmayer** [comment]
_Update:_ It seems the test failures are unrelated to this PR, as they are now also failing on current `main`: https://github.com/pelican-plugins/pandoc-reader/actions/runs/5442444514/jobs/9897675790

**Comment by nandac** [comment]
Thanks @justinmayer I will take a look into it and make a fix soon.

**Comment by nandac** [comment]
@justinmayer I have pushed up a pull request on which all the tests now pass but the pre-commit.ci pr test fails.

I need some help in this regard so that I can push to main and integrate your changes and perhaps create a new release.

**Comment by nandac** [comment]
Merging your pull-request.

**Pull request merged**
