### PR TITLE
Remove citations extension check

### PR DESCRIPTION
**Pull request by nandac**

### CODE REVIEW

**Comment by nandac** [comment]
@justinmayer Would you mind reviewing this commit and publishing a new release? This fixes a bug regarding citation support.

Release notes could be:
Removed check for +citations as it is enabled by default.

**Comment by nandac** [comment]
@justinmayer Could you please review and create a new release of this plugin.

**Comment by justinmayer** [comment]
Apologies for the delay, Nanda. I’ll have a look shortly.

**Review by justinmayer — APPROVED** [review]

**Comment by justinmayer** [comment]
Nice work, Nanda. Merged manually and released as v1.0.1. 🎉

**Comment by nandac** [comment]
Thanks @justinmayer.

**Pull request closed without merging**
